"""Update models..

Revision ID: 52f20a61efe8
Revises: 5b414e24455b
Create Date: 2024-12-19 18:20:30.459548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52f20a61efe8'
down_revision: Union[str, None] = '5b414e24455b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_currency_prices_guid', table_name='currency_prices')
    op.drop_table('currency_prices')
    op.add_column('users', sa.Column('pin', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin')
    op.create_table('currency_prices',
    sa.Column('guid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('current_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['current_id'], ['currencies.guid'], name='currency_prices_current_id_fkey'),
    sa.PrimaryKeyConstraint('guid', name='currency_prices_pkey')
    )
    op.create_index('ix_currency_prices_guid', 'currency_prices', ['guid'], unique=False)
    # ### end Alembic commands ###
