"""Remove unique parameter

Revision ID: 5f51904be260
Revises: adf91c06d3ec
Create Date: 2024-11-02 15:52:56.126215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f51904be260'
down_revision: Union[str, None] = 'adf91c06d3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_account_number_key', 'accounts', type_='unique')
    op.drop_index('ix_accounts_account_name', table_name='accounts')
    op.create_index(op.f('ix_accounts_account_name'), 'accounts', ['account_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_account_name'), table_name='accounts')
    op.create_index('ix_accounts_account_name', 'accounts', ['account_name'], unique=True)
    op.create_unique_constraint('accounts_account_number_key', 'accounts', ['account_number'])
    # ### end Alembic commands ###
