"""Changed recipient_method to receiving_method.

Revision ID: a1be3e0b28a9
Revises: d6f668cb12d2
Create Date: 2024-11-13 21:42:13.245830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1be3e0b28a9'
down_revision: Union[str, None] = 'd6f668cb12d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('receiving_method', sa.String(), nullable=False))
    op.drop_column('transactions', 'recipient_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('recipient_method', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'receiving_method')
    # ### end Alembic commands ###
