"""Update receiving method field

Revision ID: c6c4b7b65943
Revises: ddf343acd170
Create Date: 2024-11-06 16:12:45.717580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c4b7b65943'
down_revision: Union[str, None] = 'ddf343acd170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receiving_methods', sa.Column('required_card_number', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receiving_methods', 'required_card_number')
    # ### end Alembic commands ###
