"""Update Transaction model.

Revision ID: d6f668cb12d2
Revises: 3b100d637cb8
Create Date: 2024-11-13 17:54:35.625398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6f668cb12d2'
down_revision: Union[str, None] = '3b100d637cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('from_country', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('to_country', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('payment_method', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('recipient_method', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('status', sa.Enum('INITIATED', 'PENDING', 'COMPLETED', 'CANCELLED', name='transactionstatus'), nullable=False))
    op.drop_constraint('transactions_receiving_currency_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_sending_currency_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_receiving_country_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_sending_method_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_receiving_method_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_sending_country_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'receiving_country_id')
    op.drop_column('transactions', 'transaction_status')
    op.drop_column('transactions', 'receiving_currency_id')
    op.drop_column('transactions', 'receiving_method_id')
    op.drop_column('transactions', 'sending_currency_id')
    op.drop_column('transactions', 'sending_method_id')
    op.drop_column('transactions', 'sending_country_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sending_country_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('sending_method_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('sending_currency_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('receiving_method_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('receiving_currency_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('transaction_status', postgresql.ENUM('INITIATED', 'PENDING', 'COMPLETED', 'CANCELLED', name='transactionstatus'), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('receiving_country_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('transactions_sending_country_id_fkey', 'transactions', 'countries', ['sending_country_id'], ['guid'])
    op.create_foreign_key('transactions_receiving_method_id_fkey', 'transactions', 'receiving_methods', ['receiving_method_id'], ['guid'])
    op.create_foreign_key('transactions_sending_method_id_fkey', 'transactions', 'sending_methods', ['sending_method_id'], ['guid'])
    op.create_foreign_key('transactions_receiving_country_id_fkey', 'transactions', 'countries', ['receiving_country_id'], ['guid'])
    op.create_foreign_key('transactions_sending_currency_id_fkey', 'transactions', 'currencies', ['sending_currency_id'], ['guid'])
    op.create_foreign_key('transactions_receiving_currency_id_fkey', 'transactions', 'currencies', ['receiving_currency_id'], ['guid'])
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'recipient_method')
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'to_country')
    op.drop_column('transactions', 'from_country')
    # ### end Alembic commands ###
