"""Update Sending method field

Revision ID: ddf343acd170
Revises: 072de09f9f96
Create Date: 2024-11-06 15:03:11.074153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf343acd170'
down_revision: Union[str, None] = '072de09f9f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sending_methods', sa.Column('number', sa.String(), nullable=False))
    op.add_column('sending_methods', sa.Column('owner_name', sa.String(), nullable=False))
    op.drop_constraint('sending_methods_account_guid_fkey', 'sending_methods', type_='foreignkey')
    op.drop_column('sending_methods', 'account_guid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sending_methods', sa.Column('account_guid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('sending_methods_account_guid_fkey', 'sending_methods', 'accounts', ['account_guid'], ['guid'])
    op.drop_column('sending_methods', 'owner_name')
    op.drop_column('sending_methods', 'number')
    # ### end Alembic commands ###
